# Main Database Connection String
DB_URL: merico:merico@tcp(localhost:3306)/lake?charset=utf8mb4&loc=Asia%2fShanghai&parseTime=True

# Rest configuration
# Rest api port
PORT: :8080
# Rest api mode
MODE: debug
