---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devlake.fullname" . }}-config
data:
  MYSQL_USER: "{{ .Values.mysql.username }}"
  MYSQL_PASSWORD: "{{ .Values.mysql.password }}"
  MYSQL_DATABASE: "{{ .Values.mysql.database }}"
  MYSQL_ROOT_PASSWORD: "{{ .Values.mysql.rootPassword }}"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "devlake.fullname" . }}-grafana-config
data:
  grafana.ini: |
    [server]
    {{- if .Values.ingress.enabled }}
    domain = {{ .Values.ingress.hostname }}
    root_url = {{ include "devlake.grafanaEndpoint" . }}
    serve_from_sub_path = true
    {{- end }}
