version: "3"
services:
  sync:
    image: mericodev/lake:latest
    volumes:
      - ./req.json:/bin/app/req.json
    # This command will request task api every 60 mins 
    command: lake-cli api task -m POST --cron "@every 60m" --body /bin/app/req.json 
    network_mode: host
