name: lint-commit-message
on: [pull_request]

jobs:
  commit-msg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache lint-commit-message
        id: cache-lint-commit-message
        uses: actions/cache@v3
        with:
          path: lint-commit-message
          key: ${{ runner.os }}-lint-commit-message
      #- uses: wagoid/commitlint-github-action@v4
      - name: Lint commit message
        run: |
          ! git log --oneline ${{ github.event.pull_request.base.sha }}... \
            | grep -vP '^\w{8} Merge ' \
            | grep -vP '^\w{8} (feat|fix|build|chore|docs|style|refactor|perf|test|ci)(\(\w+\))?: \w'
