name: Frontend-Lint
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: cd config-ui; npm i
    - name: Run ESLint
      run: cd config-ui; npm run lint
